name: Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
          - 3.2
          - truffleruby-head

    steps:
      - uses: actions/checkout@v3

      - uses: gjtorikian/actions/setup-ruby-and-rust@main
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Compile comrak
        run: bundle exec rake compile

      - name: Run Ruby tests
        run: bundle exec rake test
